jenkisnfile agentes12

diff --git a/Jenkinsfile_agentes b/Jenkinsfile_agentes
--- a/Jenkinsfile_agentes
+++ b/Jenkinsfile_agentes
@@ -77,15 +77,25 @@ pipeline {
                                    --no-confirm-changeset \
                                    --capabilities CAPABILITY_IAM || \
                                    if [ $? -eq 1 ]; then echo "No changes to deploy, continuing..."; else exit 1; fi
+                        
+                        # Asegurar que la URL se guarda correctamente en el archivo
+                        export BASE_URL=$(aws cloudformation describe-stacks \
+                            --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='BaseUrlApi'].OutputValue" --output text)
+                        
+                        if [ -z "$BASE_URL" ]; then
+                            echo "Error: No se obtuvo la Base URL"
+                            exit 1
+                        fi
+                        
+                        echo $BASE_URL > base_url.txt
+                        echo "Base URL guardada en ${WORKSPACE}/base_url.txt"
                     '''
                     stash includes: 'base_url.txt', name: 'base_url'
                 }
             }
         }
 
-
-
-         stage('Rest Test') {
+        stage('Rest Test') {
             agent { label 'agent2' }
             steps {
                 script {
@@ -96,8 +106,8 @@ pipeline {
                         echo ${WORKSPACE}
 
                         # Verificar que el archivo existe antes de leerlo
-                        if [ -f ${WORKSPACE}/base_url.txt ]; then
-                            export BASE_URL=$(cat ${WORKSPACE}/base_url.txt)
+                        if [ -f base_url.txt ]; then
+                            export BASE_URL=$(cat base_url.txt)
                             echo "Base URL: $BASE_URL"
                         else
                             echo "Error: No se encontró base_url.txt en ${WORKSPACE}"
@@ -110,9 +120,6 @@ pipeline {
                 }
             }
         }
-
-
-
 
         stage('Promote') {
             agent any 
